export { Spot } from './spot.js';
export type { PlainSpot } from './spot.js';
export { FollowGraph } from './follow.js';
export type { PlainFollow } from './follow.js';
export { RarityIndex } from './rarity.js';
export type { RarityScore, RarityBand, Confidence, PlainRarityIndex } from './rarity.js';
export { FeedSnapshot, isAirborne } from './feed.js';
export type { FeedAircraft } from './feed.js';
export { SpotLog, DEFAULT_COOLDOWN_MS, DEFAULT_MAX_CONTACT_AGE_SEC } from './spot-log.js';
export type { SpotInput, SpotResult, SpotAccepted, SpotRejected, SpotRejectionReason, SpotLogOptions } from './spot-log.js';
export { spotAccepted, spotRejected } from './spot-log.js';
export { recentSpots, spotsBySpotter, spotsFromFollowing, spotsSince, byRecency, DEFAULT_LIMIT } from './queries.js';
